{% set name = "parsedatetime" %}
{% set version = "2.4" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "3d817c58fb9570d1eec1dd46fa9448cd644eeed4fb612684b02dfda3a79cb84b" %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner

  run:
    - python

test:
  imports:
    - parsedatetime
    - parsedatetime.pdt_locales

about:
  home: https://github.com/bear/parsedatetime
  license_file: LICENSE.txt
  license: Apache 2.0
  license_family: Apache
  summary: 'Parse human-readable date/time text.'
  dev_url: https://github.com/bear/parsedatetime
  doc_url: https://bear.im/code/parsedatetime/docs/index.html

extra:
  recipe-maintainers:
    - pmlandwehr
