travis:
  secure:
    BINSTAR_TOKEN: Unf3hM2M0Z7HMOq59k0R3mUDZrR4cL3lX/XWNk0GBGiRLLIK84Uez1llH9OLSzVAGVntzU7iVK468GNVRqOZSUaSxLSikl7a+HUq4EG0JEi0jCPAyrLTHC1WGOkn3TzxK+HD2UVlWfK/UoAP25kYo/9gIcuBfz3InNkyxbyik0hCwh7fxDA/vtjSP63+ev0a5ioQA4wj1hrbbBs4X5S5F0sxSu61td89ju6f11CJTw2zRZMkRasmBmFZ+41wJzEY4BK0jl/zIiOVwgMs2MFWIdOXF5VRrRcCJB63NF/pH5qgLjCiasj37sp+KvS1otNo52vfSYbQ32GRWD5gQ542QJaBSRGWWHu6QMa7/TpzAgrQT0CM2xOuz9YkdDaxREV0wAIEyCEMfxeHrO76/HuIlCb9McGFjxpdlIz8JeMtoJG+ClHecrGELRKM5IRKGNiFP2bwl7L8/NL95IbbVL6JCY6Zabc86gZENvjmVo8Z0HSxTgk9e2t/19crS61A/wc3em0laW4qeNhHjl/8ldDmatSkjKtRxTtm6urWICxdcSRQusUw4tmJ1gCsLNF3JRpCEVxJQfu49kUmkr5JI3pmA8wF3DAufMRSVAh5mZg3a9EqVv8H6MQuOGXhvWIo/Kkh5DsxcMvZklra9kAlRuuy22OHed0oRZvUhLgpFv3Q+9E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
