travis:
  secure:
    BINSTAR_TOKEN: Lkqh7B0trmG87kfuf+gOnxTdU6nNBcMt7Th6q+gaIap5pyyHsez1oXrcqKYsrOEB86hyZja8pqiFaZpwCrVWqbBZldcVer6Db7Rs0FyxAEss1o//6lbaAKkamtjKf89y1WD6QFVFnOZrZvPOIFHVerbFZQZbpxRP0pzMNkd4V5Fz177K5kFtQ5/NJpGrl2qPac6MEjNFX2CJZoNUH+t0T6wlWT6iQa2AVw1awPv6tnszWrIijs1W5V8sz4eyaxWma5EVjSWzlopuRZIaagxjkBWNrdAytmP5BR0KyeXb9n9msykb+bQIJYY61XApsIx471TPUo0geNY4UrbG5TQpkO5e226SqM5k7qstUoH/WFZRdACdCDWIbBQcZU8Yw6LEc2xt40sv2ZDd2SKO19J4d6kFkGQLH6m6asnbOwdfZntvQcbAPA2Khcyo4ukU7VZC4cGMXdlUevV3Ay04QDfAV+66Tu6tR02dTRdufc+fkeK3D0Y7YJGXnvFbesdo0gbNxQAaaR/IZhCdLmK/yYW+jbfSEMIARDIWp6heQRDuDBoB+NOYzEFRrQxZ4fRHk3pNdCuOIeccpSi7ZtetpA9A1xEmuUc8OWuxTf6sAmK6aysxlIgbmAwBhU2Wap2ScnuBUSwlwtX8CXpqi0ar5pgHiqUcfueoFwOKapzT/GV9Sik=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
